In [4]:
import pandas as pd

I deleted the header from the csv file because the program couldn't read it correctly and it caused an error when I tried to create the dummy variables.
Then, I created the column names using the following code statement.

We read here the csv file without header

In [36]:
# Read the CSV as a single column
df = pd.read_csv("scheduling_results_20241219_test_version.csv", header=None)

# Split into multiple columns using the semicolon as a delimiter
df = df[0].str.split(';', expand=True)

We add the column names to the data frame by the following code

In [37]:
# Assign proper column names
df.columns = ['instance', 'jobs', 'machines', 'strategy', 'tw', 'compression', 
              'overlapping', 'interrupted_calls', 'makespan', 'gap_to_opt_percent', 'opt_class']

# Verify the DataFrame
print(df.head())

  instance jobs machines strategy tw compression overlapping  \
0     TA51   50       15    EST-M  2         Yes          No
1     TA52   50       15    EST-M  2         Yes          No
2     TA53   50       15    EST-M  2         Yes          No
3     TA54   50       15    EST-M  2         Yes          No
4     TA55   50       15    EST-M  2         Yes          No

  interrupted_calls makespan gap_to_opt_percent opt_class
0                 2     3070                 11         3
1                 2     3128                 13         3
2                 2     2956                  9         2
3                 2     3039                  7         2
4                 2     2998                 12         3

We include some machine learning libraries

In [58]:
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

We select the independent variables

In [82]:
x = df[['jobs','machines','strategy','tw','compression','overlapping','interrupted_calls']]

We convert the vairables into dummy variables

In [53]:
x = pd.get_dummies(x)
x

,jobs_100,jobs_50,machines_15,machines_20,strategy_EST-M,strategy_EST-T,strategy_MTWR-M,strategy_MTWR-T,tw_10,tw_2,...,interrupted_calls_1,interrupted_calls_10,interrupted_calls_2,interrupted_calls_3,interrupted_calls_4,interrupted_calls_5,interrupted_calls_6,interrupted_calls_7,interrupted_calls_8,interrupted_calls_9
0,False,True,True,False,True,False,False,False,False,True,...,False,False,True,False,False,False,False,False,False,False
1,False,True,True,False,True,False,False,False,False,True,...,False,False,True,False,False,False,False,False,False,False
2,False,True,True,False,True,False,False,False,False,True,...,False,False,True,False,False,False,False,False,False,False
3,False,True,True,False,True,False,False,False,False,True,...,False,False,True,False,False,False,False,False,False,False
4,False,True,True,False,True,False,False,False,False,True,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4675,False,True,False,True,False,False,False,True,True,False,...,False,False,True,False,False,False,False,False,False,False
4676,False,True,False,True,False,False,False,True,True,False,...,False,False,False,False,True,False,False,False,False,False
4677,False,True,False,True,False,False,False,True,True,False,...,False,False,False,True,False,False,False,False,False,False
4678,False,True,False,True,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
4679,False,True,False,True,False,False,False,True,True,False,...,False,False,True,False,False,False,False,False,False,False

In [80]:
# Convert the target variable to numeric and ensure it's 1D
y = label_encoder.fit_transform(df['opt_class']).ravel()

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

[2 2 1 ... 3 3 3]

In [81]:
# Train the Random Forest Classifier
classifier = RandomForestClassifier(random_state=42)
classifier.fit(x_train, y_train)

# Evaluate the model
y_pred = classifier.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.6634615384615384

Classification Report:
               precision    recall  f1-score   support

           0       0.33      0.09      0.15        32
           1       0.54      0.63      0.58       113
           2       0.65      0.73      0.69       303
           3       0.71      0.73      0.72       349
           4       0.69      0.43      0.53       112
           5       0.88      0.81      0.85        27

    accuracy                           0.66       936
   macro avg       0.63      0.57      0.59       936
weighted avg       0.66      0.66      0.65       936